# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Post.create(title: "Samuel L. Ipsum", body: "Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb. Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass. Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb.")
Post.create(title: "Hipster Ipsum", body: "Consequat drinking vinegar retro esse fanny pack, Thundercats lumbersexual McSweeney's selfies banh mi Wes Anderson forage laborum aesthetic. Freegan adipisicing laboris master cleanse, tote bag raw denim cray fixie anim officia health goth. Pinterest taxidermy duis tousled. Cardigan magna cupidatat, Carles ullamco flexitarian tattooed. Kogi mustache meditation artisan voluptate jean shorts, cupidatat farm-to-table American Apparel hella DIY. Officia blog four loko iPhone. Cold-pressed ullamco readymade forage actually, vegan quinoa try-hard Echo Park. Banjo biodiesel Godard vero health goth actually. Pork belly single-origin coffee flannel, laboris sriracha fanny pack elit vinyl stumptown biodiesel meh small batch leggings est synth. Deserunt post-ironic esse, Williamsburg craft beer four dollar toast laboris vegan artisan Carles elit Neutra duis stumptown eiusmod. Tattooed squid occupy Godard. Meh cray lumbersexual, wayfarers meggings taxidermy forage occaecat umami seitan Kickstarter drinking vinegar. Magna excepteur beard officia fap, irure cray disrupt qui butcher. Nostrud odio assumenda labore Godard blog ennui voluptate.")
Post.create(title: "Yar Pirate Ipsum", body: "Jolly Roger Letter of Marque heave to bowsprit reef sails chandler loaded to the gunwalls weigh anchor Blimey fire ship. Chantey gabion barkadeer Jack Tar Sail ho Brethren of the Coast long boat yard hulk bring a spring upon her cable. Brethren of the Coast bilge jack knave rutters galleon topgallant American Main squiffy sloop. Yellow Jack tackle poop deck bowsprit bucko parley take a caulk cog dead men tell no tales run a rig. Belaying pin pirate gaff tackle reef bowsprit lugger loaded to the gunwalls brigantine tender. Lee handsomely quarter pink boatswain brigantine stern Sea Legs crow's nest bilge water. Hogshead cog fathom come about Barbary Coast quarterdeck blow the man down nipper deadlights Corsair. Provost gun hornswaggle smartly lookout fire ship Jack Ketch crow's nest strike colors weigh anchor. Lugsail yawl bilge water lee man-of-war heave down bilge measured fer yer chains bilged on her anchor gabion.")